# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "ahci" "nvme" "rtsx_pci_sdmmc"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];
  boot.kernelParams = [
    "video=HDMI-A-1:e" # Enable HDMI-A-1
    "video=eDP-1:d" # Disable laptop display (eDP-1)
  ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/d04356da-d4c0-4f7b-ac53-23c5af048ebd";
    fsType = "xfs";
  };

  fileSystems."/bin" = {
    device = "/usr/bin";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/A3DB-6B33";
    fsType = "vfat";
    options = ["fmask=0022" "dmask=0022"];
  };

  fileSystems."/mnt/nas" = {
    device = "192.168.40.11:/volume1/DiskStation54TB";
    fsType = "nfs";
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/b852d3ad-be62-4427-9ab1-89d879125cb3";}
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s20f0u1u4.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

  # For home network edns was causing issues.

  # environment.etc."resolv.conf".text = ''
  #  domain homelan.net
  #  search homelan.net
  #  nameserver 192.168.40.3
  #  nameserver 8.8.8.8
  #  options ndots:0
  #'';

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
