#!/bin/bash

rm -r ~/.config/niri/waybar/*
cp -r ~/.config/niri/waybar-alt-3/* ~/.config/niri/waybar/

# kill first
if [[ $(pidof waybar) ]]; then
	killall -q waybar
fi

while pgrep -u $UID -x waybar > /dev/null;do sleep 1;done
 

# start up again
CONFIG="$HOME/.config/niri/waybar/config.ini"
STYLE="$HOME/.config/niri/waybar/style.css"

if [[ ! $(pidof waybar) ]]; then
	waybar --bar main-bar --log-level error --config ${CONFIG} --style ${STYLE} &
fi

