#!/usr/bin/env bash

CONFIG="$HOME/.config/niri/wofifullt/config"
STYLE="$HOME/.config/niri/wofifullt/style.css"
COLORS="$HOME/.config/niri/wofifullt/colors"

if [[ ! $(pidof wofi) ]]; then
	rofi -show drun --prompt 'Search...' --conf ${CONFIG} --style ${STYLE} --color ${COLORS}
else
	pkill rofi
fi
