#!/usr/bin/env bash

CONFIG="$HOME/.config/niri/waybar-alt-2/config.ini"
STYLE="$HOME/.config/niri/waybar-alt-2/style.css"

# Create new css files and make your own style
# Here is a mono look - then change the colors

#STYLE="$HOME/.config/niri/waybar/style-mono.css"

# Terminate already running bar instances
killall -q waybar
pkill waybar

# Wait until the processes have been shut down
while pgrep -x waybar >/dev/null; do sleep 1; done

if [[ ! $(pidof waybar) ]]; then
	#waybar --bar main-bar --log-level error --config $HOME/.config/niri/waybar-alt-2/config.ini --style $HOME/.config/niri/waybar-alt-2/style.css 
	waybar --bar main-bar --log-level error --config ${CONFIG} --style ${STYLE}
fi
