name = "bar"
anchor_to_edges = true
height = 42
position = "top"

[[start]]
type = "workspaces"
all_monitors = false
on_scroll_up = "swaymsg workspace prev_on_output"
on_scroll_down = "swaymsg workspace next_on_output"

[[end]]
type = "sys_info"
format = [
    "⟮  {cpu_percent}% {temp_c:k10temp-Tccd2}°C⟯",
    "⟮  {memory_percent}%⟯",
    "⟮󰋊 {disk_percent:/}%⟯",
    "⟮󰓢 {net_down:eno1} / {net_up:eno1} Mbps⟯",
]

[end.interval]
memory = 30
cpu = 1
temps = 5
disks = 300
networks = 3

[[end]]
type = "volume"
format = "{icon} {percentage}%"
max_volume = 100
on_scroll_up = "pactl set-sink-volume @DEFAULT_SINK@ +10%"
on_scroll_down = "pactl set-sink-volume @DEFAULT_SINK@ -10%"

[end.icons]
volume_high = "󰕾"
volume_medium = "󰖀"
volume_low = "󰕿"
muted = "󰝟"

[end.truncate]
mode = "end"
length = 50

[[end]]
type = "clock"
format = "  %H:%M:%S %d/%m/%Y"

[[end]]
type = "tray"
direction = "left_to_right"

[[start]]
type = "sway_mode"

[[end]]
type = "notifications"
show_count = true

[end.icons]
closed_none = "󰍥"
closed_some = "󱥂"
closed_dnd = "󱅯"
open_none = "󰍡"
open_some = "󱥁"
open_dnd = "󱅮"

